version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend

  app:
    build: .
    command: bash -c "sleep 5 && tail -f /dev/null"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - backend

volumes:
  pgdata:

networks:
  backend: 